# Generated by Django 5.0.3 on 2024-03-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_rename_coinpurchase_product_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
